### ISSUE TITLE
Tmux Status Bar arrow color issue

### ISSUE THREAD

**Issue by c-park** [arcticicestudio/nord-tmux#40] opened 2020-04-18 19:47 UTC
The left arrows on my Tmux status bar are not being displayed correctly. I am using gnome-terminal and the Hack patched font by Nerd Fonts.

![nord](https://user-images.githubusercontent.com/3085999/79669737-ee2ad880-817a-11ea-8340-1cb518d73267.png)

**Comment by arcticicestudio** [comment] 2020-04-28 06:59
Hi @c-park :wave:

This is odd since the right side of the bar is rendered correctly.
Could you please check if this is related to #34 or #42. It looks like the _tmux_ maintainers added some breaking changes in the 2.9.x version ranges instead of publishing v3.

Also is this reproducible when use set the [`@nord_tmux_no_patched_font` theme option][d] to disable the rendering of special characters?

[d]: https://www.nordtheme.com/docs/ports/tmux/configuration#patched-font-characters

**Comment by kamushadenes** [comment] 2020-05-05 18:49
I have a similar issue, but only when tmux is notifying an activity.

![2020-05-05-1588704529_843x29_scrot](https://user-images.githubusercontent.com/242529/81103841-007d7400-8ee8-11ea-8a8b-42b3e9f1e1f8.png)

**Comment by kamushadenes** [comment] 2020-05-05 18:51
I have a similar issue, but it only happens when a non-focused tab has activity.

![2020-05-05-1588704529_843x29_scrot](https://user-images.githubusercontent.com/242529/81103999-3cb0d480-8ee8-11ea-8c3a-7e8a119dce34.png)

**Comment by c-park** [comment] 2020-05-29 02:21
I'm using tmux 2.6 on ubuntu 18.04, I can try upgrading to a more recent version of tmux.

This is what happens when I disable the special characters.so I'm guessing it is an issue with the older version of tmux.

![tmux-no-patched](https://user-images.githubusercontent.com/3085999/83214036-dd2d9980-a120-11ea-8168-2c9d8931705c.png)

**Comment by x2b7mp6** [comment] 2020-06-29 13:46
I have a similar issue, docker Alpine 3.12.0 and Tmux 3.1b

<img width="1436" alt="Screen Shot 2020-06-29 at 4 44 54 PM" src="https://user-images.githubusercontent.com/51884617/86013600-0004e380-ba28-11ea-8d1f-0beeec918d66.png">

**Comment by arcticicestudio** [comment] 2020-06-30 06:48
@x2b7mp6 This might also be related to #34, but it looks more like you're missing the required patched font. Could you please try if it works when using the [`@nord_tmux_no_patched_font` theme option][d] to disable the rendering of special characters?

[d]: https://www.nordtheme.com/docs/ports/tmux/configuration#patched-font-characters

**Comment by c-park** [comment] 2020-06-30 13:55
I was able to fix my issue by making the changes in PR #34, this was on tmux version 2.9.

**Comment by arcticicestudio** [comment] 2021-06-29 15:29
@kamushadenes @x2b7mp6 @c-park #34 has finally been merged and will be 🚀  shipped with [release version 0.4.0][1].

[1]: https://github.com/arcticicestudio/nord-tmux/milestone/5

**Closed as completed** 2021-06-29 15:31 UTC
Labels: resolution-relocated, scope-compatibility, scope-ux, type-support, context-content
